dist: trusty
sudo: required
language: python
cache:
  directories:
    - $HOME/.ccache
notifications:
  slack:
    on_success: never
    on_failure : never
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - export PATH="/usr/lib/ccache:$PATH"
  - ccache -M 256M && ccache -s
  - sudo apt-get install libgmp-dev libmpfr-dev libmpfi-dev libmpc-dev cython texlive texlive-latex-extra latexmk
  # note: sphinx in ubuntu is version 1.2.2 that does not support
  # sphinx.ext.imgmath. We just install the last version.
  - pip install sphinx
install:
  - pip install --verbose .
script:
  - python test/runtests.py
  - python test_cython/runtests.py
  - cd docs/
  - make html
  - make latexpdf
