name: pip_install_gmpy2
on:
  pull_request:
  push:
  #  branches: [master]
jobs:
  osx:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      # Try stable, latest beta, master
      # See: https://pypi.org/project/gmpy2/#history
      # Only test master for now...
      # - run: pip install gmpy2 || true
      # - run: pip install gmpy2>=2.1.0b4 || true
      - run: pip --verbose install -e .
      - run: python test/runtests.py

  linux:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        os: [ubuntu-16.04, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      # Try stable, latest beta, master
      # See: https://pypi.org/project/gmpy2/#history
      # Only test master for now...
      # - run: pip install gmpy2 || true
      # - run: pip install gmpy2>=2.1.0b4 || true
      - run: sudo apt-get install libmpc-dev texlive texlive-latex-extra latexmk
      - run: pip --verbose install -e .
      - run: python test/runtests.py

  windows:
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.7]
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd /C CALL {0}
    steps:
      - uses: actions/checkout@master
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 4.6.14
          auto-activate-base: false
          activate-environment: "test"
          channels: "conda-forge"
          python-version: ${{ matrix.python-version }}

      - name: Install libraries
        run: conda install mpir "mpfr>=4" mpc conda=4.6.14

      - name: Activate
        run: call activate test

      - name: Compile gmpy2
        run: python setup.py install build_ext --mpir -I%CONDA_PREFIX%\Library\include -L%CONDA_PREFIX%\Library\lib

      - name: Run tests
        run: cd test && python runtests.py

